### ISSUE TITLE
Problem updating facts module

### ISSUE THREAD

**Issue by rmcon** [alanshen111/facts#2]
I got this module and installed a few days ago and added some facts of my own to the facts.js file.  This morning we saw a message that the Facts module has some updates available.  The notification says "The current installation is 7 commits behind on the main branch."

(paraphrasing some of this and omitting other parts since I'm using my laptop and only looking at the RPI/MM)
I tried using git pull to get all the updates, but got a message that "Pulling without specifying how to reconcile divergent branches is discouraged..."

I see options to "git config pull.rebase false" to merge, "git config pull.rebase true" to rebase (I assume to mean it will overwrite any changes I've made) and "git config pull.ff only" no real idea what that means.

Then it says that my local changes to facts.js will be overwritten by merge and that I need to commit my changes or stash them before merge, and that it was aborting the update.

I saved a copy of the facts.js file elsewhere with the plan to reinsert the facts from my current version in case they get overwritten.  I've tried using both the merge option and the fast forward option, but the command line simply refreshes with no apparent changes.  Tried using git pull again, it doesn't give me the orange hint lines recommending some kind of action, but I get the same message that merge will overwrite my facts.js file and that it's aborting.  Just tried using the rebase option, again no apparent action takes place, but now when I try git pull, I get a message that it cannot pull with rebase, I have unstaged changes, and to commit or stash them.

What am I doing wrong?  I'm not real familiar with this kind of stuff, but have been tinkering with RPI and MM enough to get it up and functional as a family calendar display with some cool features.  I appreciate your patience and assistance.

**Comment by alanshen111** [comment]
Thanks for your comment, I'm happy that you are interested in my module!

## Simple Fix

1. Save your changes and custom facts somewhere.
2. Locate the `facts` module folder, probably in `~/MagicMirror/modules/`, and then delete the entire `facts` module folder.
3. Within the same folder, open a command line, and run `git clone https://github.com/alanshen111/facts.git`. This will clone in the latest version of the module.
4. Add back your changes and custom facts.

## Future Reference

I rarely update this module, so you will likely not need to worry about this issue reoccurring.

If you ever encounter this issue in the future or with other modules, I believe this will work: `git pull --rebase --autostash` 

This will pull in the updates, and auto stash your changes.

## Other Changes

I realize that this issue is difficult for some users to get around. I will update the `README` documentation to suggest making local changes only if one is comfortable with merging updates. Perhaps in the far future, I will come up with a surefire prevention strategy.
